# [LevelDebug = -4 LevelInfo = 0 LevelWarn = 4 LevelError = 8]
Logger:
  Level: -4

GRPCServer:
  Address: "0.0.0.0:8091"
  MaxRecvMsgSize: 8000000
  MaxSendMsgSize: 32000000

RESTServer:
  ListenPort: "8081"
  ReadTimeout: 10s
  WriteTimeout: 30s
  ShutdownTimeout: 5s
  ReadHeaderTimeout: 500ms
  IdleTimeout: 1s
  MaxHeaderBytes: 1024

AuctionService:
  Address: "localhost:9090"

AuthService:
  SocketPath: "C:/go/src/templateservice/authservice.sock"

Redis:
  Address: "localhost:6379"
  DB: 0
  Password: ""
  MaxRetries: 3
  PoolSize: 10

CacheConfig:
  AuctionDetailTTL: 10m

Kafka:
  Brokers:
    - "kafka:9092" # important to add string "127.0.0.1 kafka" to your hosts file
  Topic: "auction-events"
  GroupID: "api-gateway"
