services:
  redis:
    image: redis:7-alpine
    container_name: diploma_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  main-svc:
    build:
      context: .
      dockerfile: Dockerfile.main_svc
    container_name: main-svc
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - sockets:/sockets
      - ./config.docker.yaml:/app/config.yaml:ro
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default
      - auctionservice_default

  polling-svc:
    build:
      context: .
      dockerfile: polling_svc/Dockerfile
    container_name: polling-svc
    restart: unless-stopped
    ports:
      - "8084:8084"
    volumes:
      - sockets:/sockets
      - ./polling_svc/config.docker.yaml:/app/config.yaml:ro
    networks:
      - default
      - auctionservice_default

networks:
  default: {}
  auctionservice_default:
    external: true

volumes:
  redis_data:
  sockets:
    external: true
    name: authservice_sockets
