FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main_svc ./cmd/main.go

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/main_svc .
COPY --from=builder /app/config.yaml .
COPY --from=builder /app/credentials.yaml .
EXPOSE 8081
CMD ["./main_svc"]
