syntax = "proto3";

package auth;

option go_package = "authservice/api/auth";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest)       returns (LoginResponse);
  rpc Logout(LogoutRequest)     returns (LogoutResponse);
  rpc Refresh(RefreshRequest)   returns (RefreshResponse);
}

// ── Register ──────────────────────────────────────────────────────────────────

message RegisterRequest {
  string login    = 1;
  string password = 2;
  string email    = 3;
}

message RegisterResponse {}

// ── Login ─────────────────────────────────────────────────────────────────────

message LoginRequest {
  string login    = 1;
  string password = 2;
}

message LoginResponse {
  string access_token         = 1;
  string refresh_token        = 2;
  int64  access_token_expiry  = 3;
  int64  refresh_token_expiry = 4;
}

// ── Logout ────────────────────────────────────────────────────────────────────

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {}

// ── Refresh ───────────────────────────────────────────────────────────────────

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  string access_token         = 1;
  string refresh_token        = 2;
  int64  access_token_expiry  = 3;
  int64  refresh_token_expiry = 4;
}
