// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.1
// source: api/auction_service.proto

package auctionservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotGrpcService_CreateLot_FullMethodName = "/auctionservice.LotGrpcService/CreateLot"
	LotGrpcService_GetLot_FullMethodName    = "/auctionservice.LotGrpcService/GetLot"
	LotGrpcService_GetLots_FullMethodName   = "/auctionservice.LotGrpcService/GetLots"
	LotGrpcService_UpdateLot_FullMethodName = "/auctionservice.LotGrpcService/UpdateLot"
	LotGrpcService_DeleteLot_FullMethodName = "/auctionservice.LotGrpcService/DeleteLot"
)

// LotGrpcServiceClient is the client API for LotGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotGrpcServiceClient interface {
	CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*LotFull, error)
	GetLot(ctx context.Context, in *GetLotRequest, opts ...grpc.CallOption) (*LotFull, error)
	GetLots(ctx context.Context, in *GetLotsRequest, opts ...grpc.CallOption) (*GetLotsResponse, error)
	UpdateLot(ctx context.Context, in *UpdateLotRequest, opts ...grpc.CallOption) (*LotFull, error)
	DeleteLot(ctx context.Context, in *DeleteLotRequest, opts ...grpc.CallOption) (*DeleteLotResponse, error)
}

type lotGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotGrpcServiceClient(cc grpc.ClientConnInterface) LotGrpcServiceClient {
	return &lotGrpcServiceClient{cc}
}

func (c *lotGrpcServiceClient) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*LotFull, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LotFull)
	err := c.cc.Invoke(ctx, LotGrpcService_CreateLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotGrpcServiceClient) GetLot(ctx context.Context, in *GetLotRequest, opts ...grpc.CallOption) (*LotFull, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LotFull)
	err := c.cc.Invoke(ctx, LotGrpcService_GetLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotGrpcServiceClient) GetLots(ctx context.Context, in *GetLotsRequest, opts ...grpc.CallOption) (*GetLotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotsResponse)
	err := c.cc.Invoke(ctx, LotGrpcService_GetLots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotGrpcServiceClient) UpdateLot(ctx context.Context, in *UpdateLotRequest, opts ...grpc.CallOption) (*LotFull, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LotFull)
	err := c.cc.Invoke(ctx, LotGrpcService_UpdateLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotGrpcServiceClient) DeleteLot(ctx context.Context, in *DeleteLotRequest, opts ...grpc.CallOption) (*DeleteLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLotResponse)
	err := c.cc.Invoke(ctx, LotGrpcService_DeleteLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotGrpcServiceServer is the server API for LotGrpcService service.
// All implementations must embed UnimplementedLotGrpcServiceServer
// for forward compatibility.
type LotGrpcServiceServer interface {
	CreateLot(context.Context, *CreateLotRequest) (*LotFull, error)
	GetLot(context.Context, *GetLotRequest) (*LotFull, error)
	GetLots(context.Context, *GetLotsRequest) (*GetLotsResponse, error)
	UpdateLot(context.Context, *UpdateLotRequest) (*LotFull, error)
	DeleteLot(context.Context, *DeleteLotRequest) (*DeleteLotResponse, error)
	mustEmbedUnimplementedLotGrpcServiceServer()
}

// UnimplementedLotGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotGrpcServiceServer struct{}

func (UnimplementedLotGrpcServiceServer) CreateLot(context.Context, *CreateLotRequest) (*LotFull, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLot not implemented")
}
func (UnimplementedLotGrpcServiceServer) GetLot(context.Context, *GetLotRequest) (*LotFull, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLot not implemented")
}
func (UnimplementedLotGrpcServiceServer) GetLots(context.Context, *GetLotsRequest) (*GetLotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLots not implemented")
}
func (UnimplementedLotGrpcServiceServer) UpdateLot(context.Context, *UpdateLotRequest) (*LotFull, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLot not implemented")
}
func (UnimplementedLotGrpcServiceServer) DeleteLot(context.Context, *DeleteLotRequest) (*DeleteLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLot not implemented")
}
func (UnimplementedLotGrpcServiceServer) mustEmbedUnimplementedLotGrpcServiceServer() {}
func (UnimplementedLotGrpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotGrpcServiceServer will
// result in compilation errors.
type UnsafeLotGrpcServiceServer interface {
	mustEmbedUnimplementedLotGrpcServiceServer()
}

func RegisterLotGrpcServiceServer(s grpc.ServiceRegistrar, srv LotGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedLotGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotGrpcService_ServiceDesc, srv)
}

func _LotGrpcService_CreateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotGrpcServiceServer).CreateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotGrpcService_CreateLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotGrpcServiceServer).CreateLot(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotGrpcService_GetLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotGrpcServiceServer).GetLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotGrpcService_GetLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotGrpcServiceServer).GetLot(ctx, req.(*GetLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotGrpcService_GetLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotGrpcServiceServer).GetLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotGrpcService_GetLots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotGrpcServiceServer).GetLots(ctx, req.(*GetLotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotGrpcService_UpdateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotGrpcServiceServer).UpdateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotGrpcService_UpdateLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotGrpcServiceServer).UpdateLot(ctx, req.(*UpdateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotGrpcService_DeleteLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotGrpcServiceServer).DeleteLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotGrpcService_DeleteLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotGrpcServiceServer).DeleteLot(ctx, req.(*DeleteLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LotGrpcService_ServiceDesc is the grpc.ServiceDesc for LotGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctionservice.LotGrpcService",
	HandlerType: (*LotGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLot",
			Handler:    _LotGrpcService_CreateLot_Handler,
		},
		{
			MethodName: "GetLot",
			Handler:    _LotGrpcService_GetLot_Handler,
		},
		{
			MethodName: "GetLots",
			Handler:    _LotGrpcService_GetLots_Handler,
		},
		{
			MethodName: "UpdateLot",
			Handler:    _LotGrpcService_UpdateLot_Handler,
		},
		{
			MethodName: "DeleteLot",
			Handler:    _LotGrpcService_DeleteLot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auction_service.proto",
}

const (
	BidGrpcService_PlaceBid_FullMethodName        = "/auctionservice.BidGrpcService/PlaceBid"
	BidGrpcService_GetCurrentPrice_FullMethodName = "/auctionservice.BidGrpcService/GetCurrentPrice"
)

// BidGrpcServiceClient is the client API for BidGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidGrpcServiceClient interface {
	PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*BidProto, error)
	GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (*CurrentPriceProto, error)
}

type bidGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidGrpcServiceClient(cc grpc.ClientConnInterface) BidGrpcServiceClient {
	return &bidGrpcServiceClient{cc}
}

func (c *bidGrpcServiceClient) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*BidProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidProto)
	err := c.cc.Invoke(ctx, BidGrpcService_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bidGrpcServiceClient) GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (*CurrentPriceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentPriceProto)
	err := c.cc.Invoke(ctx, BidGrpcService_GetCurrentPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidGrpcServiceServer is the server API for BidGrpcService service.
// All implementations must embed UnimplementedBidGrpcServiceServer
// for forward compatibility.
type BidGrpcServiceServer interface {
	PlaceBid(context.Context, *PlaceBidRequest) (*BidProto, error)
	GetCurrentPrice(context.Context, *GetCurrentPriceRequest) (*CurrentPriceProto, error)
	mustEmbedUnimplementedBidGrpcServiceServer()
}

// UnimplementedBidGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidGrpcServiceServer struct{}

func (UnimplementedBidGrpcServiceServer) PlaceBid(context.Context, *PlaceBidRequest) (*BidProto, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedBidGrpcServiceServer) GetCurrentPrice(context.Context, *GetCurrentPriceRequest) (*CurrentPriceProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentPrice not implemented")
}
func (UnimplementedBidGrpcServiceServer) mustEmbedUnimplementedBidGrpcServiceServer() {}
func (UnimplementedBidGrpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeBidGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidGrpcServiceServer will
// result in compilation errors.
type UnsafeBidGrpcServiceServer interface {
	mustEmbedUnimplementedBidGrpcServiceServer()
}

func RegisterBidGrpcServiceServer(s grpc.ServiceRegistrar, srv BidGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedBidGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BidGrpcService_ServiceDesc, srv)
}

func _BidGrpcService_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidGrpcServiceServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BidGrpcService_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidGrpcServiceServer).PlaceBid(ctx, req.(*PlaceBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BidGrpcService_GetCurrentPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidGrpcServiceServer).GetCurrentPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BidGrpcService_GetCurrentPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidGrpcServiceServer).GetCurrentPrice(ctx, req.(*GetCurrentPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BidGrpcService_ServiceDesc is the grpc.ServiceDesc for BidGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctionservice.BidGrpcService",
	HandlerType: (*BidGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBid",
			Handler:    _BidGrpcService_PlaceBid_Handler,
		},
		{
			MethodName: "GetCurrentPrice",
			Handler:    _BidGrpcService_GetCurrentPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auction_service.proto",
}

const (
	SubscriptionGrpcService_Subscribe_FullMethodName         = "/auctionservice.SubscriptionGrpcService/Subscribe"
	SubscriptionGrpcService_Unsubscribe_FullMethodName       = "/auctionservice.SubscriptionGrpcService/Unsubscribe"
	SubscriptionGrpcService_GetSubscribedLots_FullMethodName = "/auctionservice.SubscriptionGrpcService/GetSubscribedLots"
)

// SubscriptionGrpcServiceClient is the client API for SubscriptionGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionGrpcServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	GetSubscribedLots(ctx context.Context, in *GetSubscribedLotsRequest, opts ...grpc.CallOption) (*GetSubscribedLotsResponse, error)
}

type subscriptionGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionGrpcServiceClient(cc grpc.ClientConnInterface) SubscriptionGrpcServiceClient {
	return &subscriptionGrpcServiceClient{cc}
}

func (c *subscriptionGrpcServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, SubscriptionGrpcService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionGrpcServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, SubscriptionGrpcService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionGrpcServiceClient) GetSubscribedLots(ctx context.Context, in *GetSubscribedLotsRequest, opts ...grpc.CallOption) (*GetSubscribedLotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscribedLotsResponse)
	err := c.cc.Invoke(ctx, SubscriptionGrpcService_GetSubscribedLots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionGrpcServiceServer is the server API for SubscriptionGrpcService service.
// All implementations must embed UnimplementedSubscriptionGrpcServiceServer
// for forward compatibility.
type SubscriptionGrpcServiceServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	GetSubscribedLots(context.Context, *GetSubscribedLotsRequest) (*GetSubscribedLotsResponse, error)
	mustEmbedUnimplementedSubscriptionGrpcServiceServer()
}

// UnimplementedSubscriptionGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionGrpcServiceServer struct{}

func (UnimplementedSubscriptionGrpcServiceServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSubscriptionGrpcServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedSubscriptionGrpcServiceServer) GetSubscribedLots(context.Context, *GetSubscribedLotsRequest) (*GetSubscribedLotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscribedLots not implemented")
}
func (UnimplementedSubscriptionGrpcServiceServer) mustEmbedUnimplementedSubscriptionGrpcServiceServer() {
}
func (UnimplementedSubscriptionGrpcServiceServer) testEmbeddedByValue() {}

// UnsafeSubscriptionGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionGrpcServiceServer will
// result in compilation errors.
type UnsafeSubscriptionGrpcServiceServer interface {
	mustEmbedUnimplementedSubscriptionGrpcServiceServer()
}

func RegisterSubscriptionGrpcServiceServer(s grpc.ServiceRegistrar, srv SubscriptionGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionGrpcService_ServiceDesc, srv)
}

func _SubscriptionGrpcService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionGrpcServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionGrpcService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionGrpcServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionGrpcService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionGrpcServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionGrpcService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionGrpcServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionGrpcService_GetSubscribedLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscribedLotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionGrpcServiceServer).GetSubscribedLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionGrpcService_GetSubscribedLots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionGrpcServiceServer).GetSubscribedLots(ctx, req.(*GetSubscribedLotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionGrpcService_ServiceDesc is the grpc.ServiceDesc for SubscriptionGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctionservice.SubscriptionGrpcService",
	HandlerType: (*SubscriptionGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _SubscriptionGrpcService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _SubscriptionGrpcService_Unsubscribe_Handler,
		},
		{
			MethodName: "GetSubscribedLots",
			Handler:    _SubscriptionGrpcService_GetSubscribedLots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auction_service.proto",
}
