// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/auction_service.proto

package auctionservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LotStatus int32

const (
	LotStatus_DRAFT  LotStatus = 0
	LotStatus_ACTIVE LotStatus = 1
	LotStatus_CLOSED LotStatus = 2
)

// Enum value maps for LotStatus.
var (
	LotStatus_name = map[int32]string{
		0: "DRAFT",
		1: "ACTIVE",
		2: "CLOSED",
	}
	LotStatus_value = map[string]int32{
		"DRAFT":  0,
		"ACTIVE": 1,
		"CLOSED": 2,
	}
)

func (x LotStatus) Enum() *LotStatus {
	p := new(LotStatus)
	*p = x
	return p
}

func (x LotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auction_service_proto_enumTypes[0].Descriptor()
}

func (LotStatus) Type() protoreflect.EnumType {
	return &file_api_auction_service_proto_enumTypes[0]
}

func (x LotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LotStatus.Descriptor instead.
func (LotStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{0}
}

// Full lot detail (returned by create / get-by-id / update)
type LotFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartingPrice string                 `protobuf:"bytes,4,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"` // decimal as string, e.g. "1500.00"
	CurrentPrice  string                 `protobuf:"bytes,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Status        LotStatus              `protobuf:"varint,6,opt,name=status,proto3,enum=auctionservice.LotStatus" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SellerId      int64                  `protobuf:"varint,8,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO-8601
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EndsAt        string                 `protobuf:"bytes,11,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotFull) Reset() {
	*x = LotFull{}
	mi := &file_api_auction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotFull) ProtoMessage() {}

func (x *LotFull) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotFull.ProtoReflect.Descriptor instead.
func (*LotFull) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{0}
}

func (x *LotFull) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LotFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LotFull) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LotFull) GetStartingPrice() string {
	if x != nil {
		return x.StartingPrice
	}
	return ""
}

func (x *LotFull) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

func (x *LotFull) GetStatus() LotStatus {
	if x != nil {
		return x.Status
	}
	return LotStatus_DRAFT
}

func (x *LotFull) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *LotFull) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *LotFull) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LotFull) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *LotFull) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

// Brief lot info (returned inside paginated list)
type LotShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CurrentPrice  string                 `protobuf:"bytes,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Status        LotStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=auctionservice.LotStatus" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	EndsAt        string                 `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotShort) Reset() {
	*x = LotShort{}
	mi := &file_api_auction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotShort) ProtoMessage() {}

func (x *LotShort) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotShort.ProtoReflect.Descriptor instead.
func (*LotShort) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{1}
}

func (x *LotShort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LotShort) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LotShort) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

func (x *LotShort) GetStatus() LotStatus {
	if x != nil {
		return x.Status
	}
	return LotStatus_DRAFT
}

func (x *LotShort) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *LotShort) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

type CreateLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartingPrice string                 `protobuf:"bytes,3,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	Status        LotStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=auctionservice.LotStatus" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SellerId      int64                  `protobuf:"varint,6,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	EndsAt        string                 `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"` // ISO-8601, empty = not set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLotRequest) Reset() {
	*x = CreateLotRequest{}
	mi := &file_api_auction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLotRequest) ProtoMessage() {}

func (x *CreateLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLotRequest.ProtoReflect.Descriptor instead.
func (*CreateLotRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLotRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLotRequest) GetStartingPrice() string {
	if x != nil {
		return x.StartingPrice
	}
	return ""
}

func (x *CreateLotRequest) GetStatus() LotStatus {
	if x != nil {
		return x.Status
	}
	return LotStatus_DRAFT
}

func (x *CreateLotRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateLotRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateLotRequest) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

type GetLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotRequest) Reset() {
	*x = GetLotRequest{}
	mi := &file_api_auction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotRequest) ProtoMessage() {}

func (x *GetLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotRequest.ProtoReflect.Descriptor instead.
func (*GetLotRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLotsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size           int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort           string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"` // field name, e.g. "createdAt"
	FilterByStatus bool                   `protobuf:"varint,4,opt,name=filter_by_status,json=filterByStatus,proto3" json:"filter_by_status,omitempty"`
	Status         LotStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=auctionservice.LotStatus" json:"status,omitempty"`
	FilterBySeller bool                   `protobuf:"varint,6,opt,name=filter_by_seller,json=filterBySeller,proto3" json:"filter_by_seller,omitempty"`
	SellerId       int64                  `protobuf:"varint,7,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLotsRequest) Reset() {
	*x = GetLotsRequest{}
	mi := &file_api_auction_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotsRequest) ProtoMessage() {}

func (x *GetLotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotsRequest.ProtoReflect.Descriptor instead.
func (*GetLotsRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetLotsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLotsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetLotsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetLotsRequest) GetFilterByStatus() bool {
	if x != nil {
		return x.FilterByStatus
	}
	return false
}

func (x *GetLotsRequest) GetStatus() LotStatus {
	if x != nil {
		return x.Status
	}
	return LotStatus_DRAFT
}

func (x *GetLotsRequest) GetFilterBySeller() bool {
	if x != nil {
		return x.FilterBySeller
	}
	return false
}

func (x *GetLotsRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

type GetLotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*LotShort            `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	TotalElements int64                  `protobuf:"varint,4,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	First         bool                   `protobuf:"varint,6,opt,name=first,proto3" json:"first,omitempty"`
	Last          bool                   `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotsResponse) Reset() {
	*x = GetLotsResponse{}
	mi := &file_api_auction_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotsResponse) ProtoMessage() {}

func (x *GetLotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotsResponse.ProtoReflect.Descriptor instead.
func (*GetLotsResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetLotsResponse) GetContent() []*LotShort {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetLotsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLotsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetLotsResponse) GetTotalElements() int64 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *GetLotsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetLotsResponse) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *GetLotsResponse) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// optional fields: only sent fields are updated (partial update)
type UpdateLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StartingPrice *string                `protobuf:"bytes,4,opt,name=starting_price,json=startingPrice,proto3,oneof" json:"starting_price,omitempty"`
	Status        *LotStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=auctionservice.LotStatus,oneof" json:"status,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	EndsAt        *string                `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3,oneof" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLotRequest) Reset() {
	*x = UpdateLotRequest{}
	mi := &file_api_auction_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLotRequest) ProtoMessage() {}

func (x *UpdateLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLotRequest.ProtoReflect.Descriptor instead.
func (*UpdateLotRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLotRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLotRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLotRequest) GetStartingPrice() string {
	if x != nil && x.StartingPrice != nil {
		return *x.StartingPrice
	}
	return ""
}

func (x *UpdateLotRequest) GetStatus() LotStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return LotStatus_DRAFT
}

func (x *UpdateLotRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateLotRequest) GetEndsAt() string {
	if x != nil && x.EndsAt != nil {
		return *x.EndsAt
	}
	return ""
}

type DeleteLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLotRequest) Reset() {
	*x = DeleteLotRequest{}
	mi := &file_api_auction_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLotRequest) ProtoMessage() {}

func (x *DeleteLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLotRequest.ProtoReflect.Descriptor instead.
func (*DeleteLotRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLotResponse) Reset() {
	*x = DeleteLotResponse{}
	mi := &file_api_auction_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLotResponse) ProtoMessage() {}

func (x *DeleteLotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLotResponse.ProtoReflect.Descriptor instead.
func (*DeleteLotResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{8}
}

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         int64                  `protobuf:"varint,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	BidderId      int64                  `protobuf:"varint,2,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // decimal as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_api_auction_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{9}
}

func (x *PlaceBidRequest) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

func (x *PlaceBidRequest) GetBidderId() int64 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *PlaceBidRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type BidProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LotId         int64                  `protobuf:"varint,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	BidderId      int64                  `protobuf:"varint,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO-8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidProto) Reset() {
	*x = BidProto{}
	mi := &file_api_auction_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidProto) ProtoMessage() {}

func (x *BidProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidProto.ProtoReflect.Descriptor instead.
func (*BidProto) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{10}
}

func (x *BidProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BidProto) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

func (x *BidProto) GetBidderId() int64 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *BidProto) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BidProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetCurrentPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         int64                  `protobuf:"varint,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPriceRequest) Reset() {
	*x = GetCurrentPriceRequest{}
	mi := &file_api_auction_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPriceRequest) ProtoMessage() {}

func (x *GetCurrentPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPriceRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentPriceRequest) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

type CurrentPriceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         int64                  `protobuf:"varint,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	CurrentPrice  string                 `protobuf:"bytes,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentPriceProto) Reset() {
	*x = CurrentPriceProto{}
	mi := &file_api_auction_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentPriceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentPriceProto) ProtoMessage() {}

func (x *CurrentPriceProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentPriceProto.ProtoReflect.Descriptor instead.
func (*CurrentPriceProto) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{12}
}

func (x *CurrentPriceProto) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

func (x *CurrentPriceProto) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LotId         int64                  `protobuf:"varint,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_auction_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeRequest) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_api_auction_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{14}
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LotId         int64                  `protobuf:"varint,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_api_auction_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{15}
}

func (x *UnsubscribeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnsubscribeRequest) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_api_auction_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{16}
}

type GetSubscribedLotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribedLotsRequest) Reset() {
	*x = GetSubscribedLotsRequest{}
	mi := &file_api_auction_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribedLotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribedLotsRequest) ProtoMessage() {}

func (x *GetSubscribedLotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribedLotsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribedLotsRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubscribedLotsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSubscribedLotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lots          []*LotShort            `protobuf:"bytes,1,rep,name=lots,proto3" json:"lots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribedLotsResponse) Reset() {
	*x = GetSubscribedLotsResponse{}
	mi := &file_api_auction_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribedLotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribedLotsResponse) ProtoMessage() {}

func (x *GetSubscribedLotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribedLotsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribedLotsResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubscribedLotsResponse) GetLots() []*LotShort {
	if x != nil {
		return x.Lots
	}
	return nil
}

var File_api_auction_service_proto protoreflect.FileDescriptor

const file_api_auction_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/auction_service.proto\x12\x0eauctionservice\"\xe1\x02\n" +
	"\aLotFull\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0estarting_price\x18\x04 \x01(\tR\rstartingPrice\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\tR\fcurrentPrice\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.auctionservice.LotStatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tseller_id\x18\b \x01(\x03R\bsellerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x17\n" +
	"\aends_at\x18\v \x01(\tR\x06endsAt\"\xbe\x01\n" +
	"\bLotShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\tR\fcurrentPrice\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.auctionservice.LotStatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x17\n" +
	"\aends_at\x18\x06 \x01(\tR\x06endsAt\"\xf7\x01\n" +
	"\x10CreateLotRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0estarting_price\x18\x03 \x01(\tR\rstartingPrice\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.auctionservice.LotStatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tseller_id\x18\x06 \x01(\x03R\bsellerId\x12\x17\n" +
	"\aends_at\x18\a \x01(\tR\x06endsAt\"\x1f\n" +
	"\rGetLotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf0\x01\n" +
	"\x0eGetLotsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12(\n" +
	"\x10filter_by_status\x18\x04 \x01(\bR\x0efilterByStatus\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.auctionservice.LotStatusR\x06status\x12(\n" +
	"\x10filter_by_seller\x18\x06 \x01(\bR\x0efilterBySeller\x12\x1b\n" +
	"\tseller_id\x18\a \x01(\x03R\bsellerId\"\xdf\x01\n" +
	"\x0fGetLotsResponse\x122\n" +
	"\acontent\x18\x01 \x03(\v2\x18.auctionservice.LotShortR\acontent\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x04 \x01(\x03R\rtotalElements\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12\x14\n" +
	"\x05first\x18\x06 \x01(\bR\x05first\x12\x12\n" +
	"\x04last\x18\a \x01(\bR\x04last\"\xda\x02\n" +
	"\x10UpdateLotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x0estarting_price\x18\x04 \x01(\tH\x02R\rstartingPrice\x88\x01\x01\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.auctionservice.LotStatusH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x06 \x01(\tH\x04R\bimageUrl\x88\x01\x01\x12\x1c\n" +
	"\aends_at\x18\a \x01(\tH\x05R\x06endsAt\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_starting_priceB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_image_urlB\n" +
	"\n" +
	"\b_ends_at\"\"\n" +
	"\x10DeleteLotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x13\n" +
	"\x11DeleteLotResponse\"]\n" +
	"\x0fPlaceBidRequest\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\x03R\x05lotId\x12\x1b\n" +
	"\tbidder_id\x18\x02 \x01(\x03R\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\x85\x01\n" +
	"\bBidProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\x03R\x05lotId\x12\x1b\n" +
	"\tbidder_id\x18\x03 \x01(\x03R\bbidderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"/\n" +
	"\x16GetCurrentPriceRequest\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\x03R\x05lotId\"O\n" +
	"\x11CurrentPriceProto\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\x03R\x05lotId\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\tR\fcurrentPrice\"B\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\x03R\x05lotId\"\x13\n" +
	"\x11SubscribeResponse\"D\n" +
	"\x12UnsubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\x03R\x05lotId\"\x15\n" +
	"\x13UnsubscribeResponse\"3\n" +
	"\x18GetSubscribedLotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"I\n" +
	"\x19GetSubscribedLotsResponse\x12,\n" +
	"\x04lots\x18\x01 \x03(\v2\x18.auctionservice.LotShortR\x04lots*.\n" +
	"\tLotStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x022\x80\x03\n" +
	"\x0eLotGrpcService\x12F\n" +
	"\tCreateLot\x12 .auctionservice.CreateLotRequest\x1a\x17.auctionservice.LotFull\x12@\n" +
	"\x06GetLot\x12\x1d.auctionservice.GetLotRequest\x1a\x17.auctionservice.LotFull\x12J\n" +
	"\aGetLots\x12\x1e.auctionservice.GetLotsRequest\x1a\x1f.auctionservice.GetLotsResponse\x12F\n" +
	"\tUpdateLot\x12 .auctionservice.UpdateLotRequest\x1a\x17.auctionservice.LotFull\x12P\n" +
	"\tDeleteLot\x12 .auctionservice.DeleteLotRequest\x1a!.auctionservice.DeleteLotResponse2\xb5\x01\n" +
	"\x0eBidGrpcService\x12E\n" +
	"\bPlaceBid\x12\x1f.auctionservice.PlaceBidRequest\x1a\x18.auctionservice.BidProto\x12\\\n" +
	"\x0fGetCurrentPrice\x12&.auctionservice.GetCurrentPriceRequest\x1a!.auctionservice.CurrentPriceProto2\xad\x02\n" +
	"\x17SubscriptionGrpcService\x12P\n" +
	"\tSubscribe\x12 .auctionservice.SubscribeRequest\x1a!.auctionservice.SubscribeResponse\x12V\n" +
	"\vUnsubscribe\x12\".auctionservice.UnsubscribeRequest\x1a#.auctionservice.UnsubscribeResponse\x12h\n" +
	"\x11GetSubscribedLots\x12(.auctionservice.GetSubscribedLotsRequest\x1a).auctionservice.GetSubscribedLotsResponseBS\n" +
	"\x1cru.auctionservice.grpc.protoP\x01Z1apigateway/api/grpc/auctionservice;auctionserviceb\x06proto3"

var (
	file_api_auction_service_proto_rawDescOnce sync.Once
	file_api_auction_service_proto_rawDescData []byte
)

func file_api_auction_service_proto_rawDescGZIP() []byte {
	file_api_auction_service_proto_rawDescOnce.Do(func() {
		file_api_auction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auction_service_proto_rawDesc), len(file_api_auction_service_proto_rawDesc)))
	})
	return file_api_auction_service_proto_rawDescData
}

var file_api_auction_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_auction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_auction_service_proto_goTypes = []any{
	(LotStatus)(0),                    // 0: auctionservice.LotStatus
	(*LotFull)(nil),                   // 1: auctionservice.LotFull
	(*LotShort)(nil),                  // 2: auctionservice.LotShort
	(*CreateLotRequest)(nil),          // 3: auctionservice.CreateLotRequest
	(*GetLotRequest)(nil),             // 4: auctionservice.GetLotRequest
	(*GetLotsRequest)(nil),            // 5: auctionservice.GetLotsRequest
	(*GetLotsResponse)(nil),           // 6: auctionservice.GetLotsResponse
	(*UpdateLotRequest)(nil),          // 7: auctionservice.UpdateLotRequest
	(*DeleteLotRequest)(nil),          // 8: auctionservice.DeleteLotRequest
	(*DeleteLotResponse)(nil),         // 9: auctionservice.DeleteLotResponse
	(*PlaceBidRequest)(nil),           // 10: auctionservice.PlaceBidRequest
	(*BidProto)(nil),                  // 11: auctionservice.BidProto
	(*GetCurrentPriceRequest)(nil),    // 12: auctionservice.GetCurrentPriceRequest
	(*CurrentPriceProto)(nil),         // 13: auctionservice.CurrentPriceProto
	(*SubscribeRequest)(nil),          // 14: auctionservice.SubscribeRequest
	(*SubscribeResponse)(nil),         // 15: auctionservice.SubscribeResponse
	(*UnsubscribeRequest)(nil),        // 16: auctionservice.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),       // 17: auctionservice.UnsubscribeResponse
	(*GetSubscribedLotsRequest)(nil),  // 18: auctionservice.GetSubscribedLotsRequest
	(*GetSubscribedLotsResponse)(nil), // 19: auctionservice.GetSubscribedLotsResponse
}
var file_api_auction_service_proto_depIdxs = []int32{
	0,  // 0: auctionservice.LotFull.status:type_name -> auctionservice.LotStatus
	0,  // 1: auctionservice.LotShort.status:type_name -> auctionservice.LotStatus
	0,  // 2: auctionservice.CreateLotRequest.status:type_name -> auctionservice.LotStatus
	0,  // 3: auctionservice.GetLotsRequest.status:type_name -> auctionservice.LotStatus
	2,  // 4: auctionservice.GetLotsResponse.content:type_name -> auctionservice.LotShort
	0,  // 5: auctionservice.UpdateLotRequest.status:type_name -> auctionservice.LotStatus
	2,  // 6: auctionservice.GetSubscribedLotsResponse.lots:type_name -> auctionservice.LotShort
	3,  // 7: auctionservice.LotGrpcService.CreateLot:input_type -> auctionservice.CreateLotRequest
	4,  // 8: auctionservice.LotGrpcService.GetLot:input_type -> auctionservice.GetLotRequest
	5,  // 9: auctionservice.LotGrpcService.GetLots:input_type -> auctionservice.GetLotsRequest
	7,  // 10: auctionservice.LotGrpcService.UpdateLot:input_type -> auctionservice.UpdateLotRequest
	8,  // 11: auctionservice.LotGrpcService.DeleteLot:input_type -> auctionservice.DeleteLotRequest
	10, // 12: auctionservice.BidGrpcService.PlaceBid:input_type -> auctionservice.PlaceBidRequest
	12, // 13: auctionservice.BidGrpcService.GetCurrentPrice:input_type -> auctionservice.GetCurrentPriceRequest
	14, // 14: auctionservice.SubscriptionGrpcService.Subscribe:input_type -> auctionservice.SubscribeRequest
	16, // 15: auctionservice.SubscriptionGrpcService.Unsubscribe:input_type -> auctionservice.UnsubscribeRequest
	18, // 16: auctionservice.SubscriptionGrpcService.GetSubscribedLots:input_type -> auctionservice.GetSubscribedLotsRequest
	1,  // 17: auctionservice.LotGrpcService.CreateLot:output_type -> auctionservice.LotFull
	1,  // 18: auctionservice.LotGrpcService.GetLot:output_type -> auctionservice.LotFull
	6,  // 19: auctionservice.LotGrpcService.GetLots:output_type -> auctionservice.GetLotsResponse
	1,  // 20: auctionservice.LotGrpcService.UpdateLot:output_type -> auctionservice.LotFull
	9,  // 21: auctionservice.LotGrpcService.DeleteLot:output_type -> auctionservice.DeleteLotResponse
	11, // 22: auctionservice.BidGrpcService.PlaceBid:output_type -> auctionservice.BidProto
	13, // 23: auctionservice.BidGrpcService.GetCurrentPrice:output_type -> auctionservice.CurrentPriceProto
	15, // 24: auctionservice.SubscriptionGrpcService.Subscribe:output_type -> auctionservice.SubscribeResponse
	17, // 25: auctionservice.SubscriptionGrpcService.Unsubscribe:output_type -> auctionservice.UnsubscribeResponse
	19, // 26: auctionservice.SubscriptionGrpcService.GetSubscribedLots:output_type -> auctionservice.GetSubscribedLotsResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_auction_service_proto_init() }
func file_api_auction_service_proto_init() {
	if File_api_auction_service_proto != nil {
		return
	}
	file_api_auction_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auction_service_proto_rawDesc), len(file_api_auction_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_auction_service_proto_goTypes,
		DependencyIndexes: file_api_auction_service_proto_depIdxs,
		EnumInfos:         file_api_auction_service_proto_enumTypes,
		MessageInfos:      file_api_auction_service_proto_msgTypes,
	}.Build()
	File_api_auction_service_proto = out.File
	file_api_auction_service_proto_goTypes = nil
	file_api_auction_service_proto_depIdxs = nil
}
